@startuml

title __MUSIC's Class Diagram__\n

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.KillMusicCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.MoveCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      interface ninja.diku.command.commands.music.MusicCommand {
          {static} + audioManager : AudioManager
          {abstract} + onCommand()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.PlayCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.PlayingCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.QueueCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.music {
      class ninja.diku.command.commands.music.SkipCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  ninja.diku.command.commands.music.KillMusicCommand .up.|> ninja.diku.command.commands.music.MusicCommand
  ninja.diku.command.commands.music.MoveCommand .up.|> ninja.diku.command.commands.music.MusicCommand
  ninja.diku.command.commands.music.PlayCommand .up.|> ninja.diku.command.commands.music.MusicCommand
  ninja.diku.command.commands.music.PlayingCommand .up.|> ninja.diku.command.commands.music.MusicCommand
  ninja.diku.command.commands.music.QueueCommand .up.|> ninja.diku.command.commands.music.MusicCommand
  ninja.diku.command.commands.music.SkipCommand .up.|> ninja.diku.command.commands.music.MusicCommand


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
