@startuml

title __TICKET's Class Diagram__\n

  namespace ninja.diku.ticket {
    abstract class ninja.diku.ticket.Ticket {
        # UUID : UUID
        # guild : Guild
        # user : User
        + Ticket()
        + activate()
        + close()
        {abstract} + getCloseDisplay()
        {abstract} + getClosedTicketChannel()
        {abstract} + getContext()
        {abstract} + getDisplay()
        + getGuild()
        {abstract} + getOpenTicketChannel()
        {static} + getTicket()
        {abstract} + getType()
        + getUUID()
        + getUser()
    }
  }
  

  namespace ninja.diku.ticket {
    enum Type {
      GENERIC
      MAJOR
      ticket
    }
  }
  

  namespace ninja.diku.ticket {
    interface ninja.diku.ticket.TicketAction {
        {abstract} + command()
        {abstract} + execute()
    }
  }
  

  namespace ninja.diku.ticket {
    class ninja.diku.ticket.TicketDisplay {
        - actions : HashMap<String, TicketAction>
        - message : Message
        - user : User
        + getActions()
        + getMessage()
        + getUser()
        # TicketDisplay()
    }
  }
  

  namespace ninja.diku.ticket {
    class ninja.diku.ticket.TicketDisplay.Builder {
        - actions : HashMap<String, TicketAction>
        - message : Message
        - user : User
        + addAction()
        + build()
        + getActions()
        + getMessage()
        + getUser()
        + setMessage()
        + setUser()
    }
  }
  

  namespace ninja.diku.ticket {
    class ninja.diku.ticket.TicketFactory {
        {static} + getTicket()
    }
  }
  

  namespace ninja.diku.ticket {
    class ninja.diku.ticket.TicketListener {
        + onGuildMessageReactionAdd()
    }
  }
  

  ninja.diku.ticket.Ticket +-down- ninja.diku.ticket.Ticket.Type
  ninja.diku.ticket.TicketDisplay +-down- ninja.diku.ticket.TicketDisplay.Builder
  ninja.diku.ticket.TicketListener -up-|> net.dv8tion.jda.api.hooks.ListenerAdapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
