@startuml

title __FUN's Class Diagram__\n

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.LoveCalcCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.Magic8BallCommand {
          {static} ~ answers : String[]
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.PingCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.PrimeCommand {
          + getDescription()
          + getUsage()
          + onCommand()
          - getRandomPrime()
          - isPrime()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.ProdigyCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.QuoteCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.RPNCommand {
          {static} + calculate()
          {static} + calculate()
          + getDescription()
          + getUsage()
          + onCommand()
          {static} - calc()
          {static} - isDouble()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.fun {
      class ninja.diku.command.commands.fun.RollCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  ninja.diku.command.commands.fun.LoveCalcCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.Magic8BallCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.PingCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.PrimeCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.ProdigyCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.QuoteCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.RPNCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.fun.RollCommand .up.|> ninja.diku.command.Command


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
