@startuml

title __UTIL's Class Diagram__\n

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.ClearCommand {
          {static} - clearable : Set<Long>
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.GroupCommand {
          + getDescription()
          + getUsage()
          + onCommand()
          - sendGroups()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.HelpCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.MyDataCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.ResetCommand {
          + getDescription()
          + getUsage()
          + onCommand()
          - resetUser()
      }
    }
  }
  

  namespace ninja.diku.command {
    namespace commands.util {
      class ninja.diku.command.commands.util.TicketCommand {
          + getDescription()
          + getUsage()
          + onCommand()
      }
    }
  }
  

  ninja.diku.command.commands.util.ClearCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.util.GroupCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.util.HelpCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.util.MyDataCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.util.ResetCommand .up.|> ninja.diku.command.Command
  ninja.diku.command.commands.util.TicketCommand .up.|> ninja.diku.command.Command


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
